name: Flutter Android CD
on:
  push:
    tags:
      - android-v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build_deploy_android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Flutter setup
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.x'
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Decrypt Android keys
        run: sh ./.github/scripts/decrypt_android_keys.sh
        env:
          ANDROID_KEYS_SECRET_PASSPHRASE: ${{ secrets.ANDROID_KEYS_SECRET_PASSPHRASE }}
      - name: Build the appbundle
        run: flutter build appbundle
      - name: Upload artifact on github
        uses: actions/upload-artifact@v2
        with:
          name: release-appbundle
          path: build/app/outputs/bundle/release/app-release.aab
      - name: Run Fastlane
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: deploy_internal
          subdirectory: android

  create_release:
    runs-on: ubuntu-latest
    needs: [build_deply_android]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
